dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libglm-dev libglew-dev xorg-dev
- git clone https://github.com/glfw/glfw && cd glfw && mkdir build && cd build && cmake .. && make -j4 && sudo make install

script:
  - pwd
  - cd ../..
  - mkdir build
  - cd build
  - cmake ..
  - make
