dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

before_install:
- sudo apt-get -qq update
- sudo apt-get remove --auto-remove cmake
- sudo apt-get install -y libglm-dev libglew-dev xorg-dev
- wget https://cmake.org/files/v3.9/cmake-3.9.5-Linux-x86_64.tar.gz
- tar -xvf cmake-3.9.5-Linux-x86_64.tar.gz
- export PATH=$PATH:$PWD/cmake-3.9.5-Linux-x86_64/bin/
- git clone https://github.com/glfw/glfw && cd glfw && mkdir build && cd build && cmake .. && make -j4 && sudo make install
- cd ../../..

script:
  - pwd
  - ls
  - cd PBF_15418
  - mkdir build
  - cd build
  - cmake ..
  - make
